<a href="https://colab.research.google.com/github/vicar1987/Data_Mining_class_practice/blob/main/DataMining_Numpy_%E8%8E%8A%E8%82%B2%E4%BF%AE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#寫程式計算以下值
import numpy as np
x = np.array([[1, 3, 5], [2, 4, 6]], np.int32)
#計算
#type(x)
#x.shape
#x.dtype
#x[:,1]
A = np.array([[3,2],[0,1]])
B = np.array([[3,1],[2,1]])
#求
#A+B
#A*B
#A@B
#A的轉置矩陣
#B的反矩陣

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1, 3, 5], [2, 4, 6]], np.int32)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.shape #形狀(矩陣中的維度及各維度大小)

(2, 3)

In [ ]:
x.dtype #資料類別

dtype('int32')

In [ ]:
x[:,1] 
#只取中間那一行
#[1 ,3 ,5]
#[2 ,4 ,6]

array([3, 4])

In [ ]:
A = np.array([[3,2],[0,1]])
B = np.array([[3,1],[2,1]])

In [ ]:
A + B

array([[6, 3],
       [2, 2]])

In [ ]:
A * B

array([[9, 2],
       [0, 1]])

In [ ]:
A @ B

array([[13,  5],
       [ 2,  1]])

In [ ]:
A.transpose() #A的轉置矩陣

array([[3, 0],
       [2, 1]])

In [ ]:
np.linalg.inv(B) #B的反矩陣

array([[ 1., -1.],
       [-2.,  3.]])